"""Training utilities for RSNA neural foraminal narrowing (P10.6-AI).

This module trains a human-in-the-loop research classifier from the train and
validation manifests generated by Notebook 58. It deliberately does not read
the internal-test manifest.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import random
import shutil
import subprocess
import sys
import time
import zipfile
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path, PurePosixPath
from typing import Any, Iterable

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.metrics import balanced_accuracy_score, f1_score, log_loss, recall_score
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from tqdm.auto import tqdm


CLASS_NAMES = ("normal_mild", "moderate", "severe")
CLASS_TO_INDEX = {name: index for index, name in enumerate(CLASS_NAMES)}
DISPLAY_CLASS_NAMES = ("Normal/Mild", "Moderate", "Severe")
SIDES = ("left", "right")
SIDE_TO_INDEX = {name: index for index, name in enumerate(SIDES)}
LEVELS = ("L1-L2", "L2-L3", "L3-L4", "L4-L5", "L5-S1")
LEVEL_TO_INDEX = {name: index for index, name in enumerate(LEVELS)}
REQUIRED_MANIFEST_COLUMNS = {
    "study_id",
    "side",
    "level",
    "severity",
    "severity_code",
    "coordinate_series_id",
    "coordinate_instance_number",
    "coordinate_x",
    "coordinate_y",
    "coordinate_series_description",
    "split",
    "internal_test_sealed",
    "human_review_required",
    "not_clinical_diagnosis",
    "official_test_accessed",
}


@dataclass(frozen=True)
class TrainConfig:
    seed: int = 2026
    image_size: int = 224
    crop_size: int = 256
    batch_size: int = 32
    num_workers: int = 2
    max_epochs: int = 15
    patience: int = 5
    learning_rate: float = 2e-4
    weight_decay: float = 1e-4
    model_name: str = "efficientnet_b0"
    pretrained: bool = True
    side_embedding_dim: int = 8
    level_embedding_dim: int = 12
    dropout: float = 0.25
    label_smoothing: float = 0.05
    severe_loss_multiplier: float = 1.25
    max_grad_norm: float = 2.0
    minimum_macro_f1: float = 0.36
    minimum_balanced_accuracy: float = 0.45
    minimum_severe_recall: float = 0.30
    minimum_moderate_recall: float = 0.25


@dataclass(frozen=True)
class DataRootAudit:
    root: str
    complete: bool
    required_series: int
    missing_series: int
    missing_examples: tuple[str, ...]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.parent / f".{path.name}.tmp"
    try:
        temporary.write_text(text, encoding="utf-8", newline="\n")
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _atomic_write_json(path: Path, payload: Any) -> None:
    _atomic_write_text(
        path,
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
    )


def _parse_bool(series: pd.Series) -> pd.Series:
    return (
        series.astype(str)
        .str.strip()
        .str.lower()
        .isin({"true", "1", "yes"})
    )


def _validate_summary(summary: dict[str, Any]) -> None:
    if summary.get("approved") is not True:
        raise RuntimeError("El Notebook 58 no está aprobado.")
    if summary.get("nextNotebook") != 59:
        raise RuntimeError("El Notebook 58 no habilita el Notebook 59.")
    governance = summary.get("governance", {})
    gates = summary.get("gateResults", {})
    if governance.get("internalTestSealed") is not True:
        raise RuntimeError("El internal test no figura sellado.")
    if governance.get("officialTestAccessed") is not False:
        raise RuntimeError("El Notebook 58 declara acceso al test oficial.")
    if gates.get("noStudyLeakage") is not True:
        raise RuntimeError("El split de Notebook 58 no aprobó el gate de fuga.")


def _normalize_manifest(frame: pd.DataFrame, expected_split: str) -> pd.DataFrame:
    missing = sorted(REQUIRED_MANIFEST_COLUMNS - set(frame.columns))
    if missing:
        raise RuntimeError(f"Faltan columnas en {expected_split}: {missing}")

    result = frame.copy()
    result["study_id"] = result["study_id"].astype(str)
    result["coordinate_series_id"] = result["coordinate_series_id"].astype(str)
    result["side"] = result["side"].astype(str).str.strip().str.lower()
    result["level"] = result["level"].astype(str).str.strip()
    result["severity"] = result["severity"].astype(str).str.strip().str.lower()
    result["split"] = result["split"].astype(str).str.strip()

    for column in (
        "coordinate_instance_number",
        "coordinate_x",
        "coordinate_y",
        "severity_code",
    ):
        result[column] = pd.to_numeric(result[column], errors="coerce")

    if result[[
        "coordinate_instance_number",
        "coordinate_x",
        "coordinate_y",
        "severity_code",
    ]].isna().any().any():
        bad = result[[
            "coordinate_instance_number",
            "coordinate_x",
            "coordinate_y",
            "severity_code",
        ]].isna().sum().to_dict()
        raise RuntimeError(f"Valores numéricos inválidos en {expected_split}: {bad}")

    result["coordinate_instance_number"] = (
        result["coordinate_instance_number"].round().astype(int)
    )
    result["severity_code"] = result["severity_code"].round().astype(int)

    if not result["split"].eq(expected_split).all():
        raise RuntimeError(f"Hay filas con split incorrecto en {expected_split}.")
    if not result["side"].isin(SIDES).all():
        raise RuntimeError(f"Lateralidad inválida en {expected_split}.")
    if not result["level"].isin(LEVELS).all():
        raise RuntimeError(f"Nivel inválido en {expected_split}.")
    if not result["severity"].isin(CLASS_NAMES).all():
        raise RuntimeError(f"Severidad inválida en {expected_split}.")

    expected_codes = result["severity"].map(CLASS_TO_INDEX).astype(int)
    if not expected_codes.eq(result["severity_code"]).all():
        raise RuntimeError(f"severity_code inconsistente en {expected_split}.")

    if result[["study_id", "side", "level"]].duplicated().any():
        raise RuntimeError(
            f"Hay claves study_id-side-level duplicadas en {expected_split}."
        )

    if not result["coordinate_series_description"].astype(str).str.strip().eq(
        "Sagittal T1"
    ).all():
        raise RuntimeError(f"Hay secuencias distintas de Sagittal T1 en {expected_split}.")

    if _parse_bool(result["official_test_accessed"]).any():
        raise RuntimeError(f"official_test_accessed=true en {expected_split}.")
    if not _parse_bool(result["human_review_required"]).all():
        raise RuntimeError(f"human_review_required no es true en {expected_split}.")
    if not _parse_bool(result["not_clinical_diagnosis"]).all():
        raise RuntimeError(f"not_clinical_diagnosis no es true en {expected_split}.")

    result["side_index"] = result["side"].map(SIDE_TO_INDEX).astype(int)
    result["level_index"] = result["level"].map(LEVEL_TO_INDEX).astype(int)
    result["sample_id"] = (
        result["study_id"]
        + "__"
        + result["side"]
        + "__"
        + result["level"].str.replace("-", "_", regex=False)
    )
    result["stratum"] = (
        result["side"] + "__" + result["level"] + "__" + result["severity"]
    )
    return result.reset_index(drop=True)


def load_manifests(
    split_root: Path,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any], dict[str, str]]:
    """Load only train and validation; internal_test is existence-checked, not read."""
    train_path = split_root / "train_manifest.csv"
    validation_path = split_root / "validation_manifest.csv"
    internal_test_path = split_root / "internal_test_manifest.csv"
    summary_path = split_root / "split_summary.json"
    required = [train_path, validation_path, internal_test_path, summary_path]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise RuntimeError("Faltan artefactos del Notebook 58:\n- " + "\n- ".join(missing))

    with summary_path.open("r", encoding="utf-8") as handle:
        summary = json.load(handle)
    _validate_summary(summary)

    hashes = {
        "train_manifest": sha256_file(train_path),
        "validation_manifest": sha256_file(validation_path),
        "split_summary": sha256_file(summary_path),
    }
    expected_hashes = summary.get("outputSha256", {})
    expected_train = expected_hashes.get("trainManifest")
    expected_validation = expected_hashes.get("validationManifest")
    if expected_train and hashes["train_manifest"] != expected_train:
        raise RuntimeError("Hash de train_manifest no coincide con Notebook 58.")
    if expected_validation and hashes["validation_manifest"] != expected_validation:
        raise RuntimeError("Hash de validation_manifest no coincide con Notebook 58.")

    train = _normalize_manifest(
        pd.read_csv(train_path, dtype={"study_id": str, "coordinate_series_id": str}),
        "train",
    )
    validation = _normalize_manifest(
        pd.read_csv(
            validation_path,
            dtype={"study_id": str, "coordinate_series_id": str},
        ),
        "validation",
    )

    overlap = sorted(set(train["study_id"]) & set(validation["study_id"]))
    if overlap:
        raise RuntimeError(f"Fuga train-validation: {overlap[:10]}")
    if set(train["severity"]) != set(CLASS_NAMES):
        raise RuntimeError("Train no contiene las tres clases.")
    if set(validation["severity"]) != set(CLASS_NAMES):
        raise RuntimeError("Validation no contiene las tres clases.")

    declared = summary.get("splits", {})
    if int(declared.get("train", {}).get("rows", -1)) != len(train):
        raise RuntimeError("Cantidad de filas train distinta a split_summary.")
    if int(declared.get("validation", {}).get("rows", -1)) != len(validation):
        raise RuntimeError("Cantidad de filas validation distinta a split_summary.")

    return train, validation, summary, hashes


def required_series_table(*frames: pd.DataFrame) -> pd.DataFrame:
    combined = pd.concat(
        [
            frame[["study_id", "coordinate_series_id"]]
            for frame in frames
        ],
        ignore_index=True,
    )
    return (
        combined.drop_duplicates()
        .sort_values(["study_id", "coordinate_series_id"])
        .reset_index(drop=True)
    )


def audit_data_root(root: Path, *frames: pd.DataFrame) -> DataRootAudit:
    required = required_series_table(*frames)
    missing: list[str] = []
    for row in required.itertuples(index=False):
        path = root / "train_images" / str(row.study_id) / str(row.coordinate_series_id)
        if not path.is_dir() or not any(path.glob("*.dcm")):
            missing.append(f"{row.study_id}/{row.coordinate_series_id}")
    return DataRootAudit(
        root=str(root),
        complete=not missing,
        required_series=int(len(required)),
        missing_series=int(len(missing)),
        missing_examples=tuple(missing[:20]),
    )


def find_data_root(
    candidates: Iterable[Path],
    train: pd.DataFrame,
    validation: pd.DataFrame,
) -> tuple[Path | None, list[DataRootAudit]]:
    audits: list[DataRootAudit] = []
    for candidate in candidates:
        audit = audit_data_root(candidate, train, validation)
        audits.append(audit)
        if audit.complete:
            return candidate, audits
    return None, audits


def download_selected_series(
    train: pd.DataFrame,
    validation: pd.DataFrame,
    local_root: Path,
    competition: str,
    kaggle_token: str,
) -> Path:
    """Download the competition archive and extract only required Sagittal T1 series."""
    if not kaggle_token.strip():
        raise RuntimeError("No se ingresó token de Kaggle.")

    ready = audit_data_root(local_root, train, validation)
    if ready.complete:
        return local_root

    free = shutil.disk_usage("/content").free
    if free < 38 * 1024**3:
        raise RuntimeError(
            f"Espacio local insuficiente para la descarga temporal: {free / 1024**3:.1f} GiB libres."
        )

    required_pairs = {
        (str(row.study_id), str(row.coordinate_series_id))
        for row in required_series_table(train, validation).itertuples(index=False)
    }
    required_series = {series_id for _, series_id in required_pairs}
    download_root = Path("/content/rsna_foraminal_kaggle_download")
    shutil.rmtree(download_root, ignore_errors=True)
    download_root.mkdir(parents=True, exist_ok=True)
    local_root.mkdir(parents=True, exist_ok=True)

    executable = shutil.which("kaggle") or str(Path(sys.executable).parent / "kaggle")
    os.environ["KAGGLE_API_TOKEN"] = kaggle_token.strip()
    try:
        subprocess.check_call(
            [
                executable,
                "competitions",
                "download",
                competition,
                "--path",
                str(download_root),
                "--force",
            ]
        )
    finally:
        os.environ.pop("KAGGLE_API_TOKEN", None)

    archives = sorted(download_root.glob("*.zip"))
    if not archives:
        raise RuntimeError("Kaggle no produjo un archivo ZIP.")
    archive_path = max(archives, key=lambda path: path.stat().st_size)
    root_resolved = local_root.resolve()
    extracted = 0
    started = time.time()

    def selected(member_name: str) -> Path | None:
        normalized = PurePosixPath(member_name)
        if normalized.is_absolute() or ".." in normalized.parts:
            raise RuntimeError(f"Ruta insegura dentro del ZIP: {member_name!r}")
        if "train_images" not in normalized.parts:
            return None
        index = normalized.parts.index("train_images")
        parts = normalized.parts[index:]
        if len(parts) < 4:
            return None
        study_id, series_id = parts[1], parts[2]
        if series_id not in required_series or (study_id, series_id) not in required_pairs:
            return None
        return Path(*parts)

    try:
        with zipfile.ZipFile(archive_path, "r") as archive:
            for member in archive.infolist():
                if member.is_dir():
                    continue
                relative = selected(member.filename)
                if relative is None:
                    continue
                destination = (local_root / relative).resolve()
                if destination != root_resolved and root_resolved not in destination.parents:
                    raise RuntimeError("Intento de extracción fuera del directorio local.")
                if destination.exists() and destination.stat().st_size == member.file_size:
                    continue
                destination.parent.mkdir(parents=True, exist_ok=True)
                with archive.open(member) as source, destination.open("wb") as target:
                    shutil.copyfileobj(source, target, length=8 * 1024 * 1024)
                extracted += 1
                if extracted % 5000 == 0:
                    print({"dicomExtracted": extracted})
    finally:
        shutil.rmtree(download_root, ignore_errors=True)

    audit = audit_data_root(local_root, train, validation)
    if not audit.complete:
        raise RuntimeError(
            "El subconjunto Sagittal T1 quedó incompleto: "
            f"{audit.missing_series} series faltantes; ejemplos={list(audit.missing_examples)}"
        )
    print(
        {
            "selectedDicomExtracted": extracted,
            "requiredSeries": audit.required_series,
            "minutes": round((time.time() - started) / 60, 2),
        }
    )
    return local_root


def prepare_samples(frame: pd.DataFrame, data_root: Path, split: str) -> pd.DataFrame:
    result = frame.copy()
    result["local_series_path"] = result.apply(
        lambda row: str(
            data_root
            / "train_images"
            / str(row["study_id"])
            / str(row["coordinate_series_id"])
        ),
        axis=1,
    )
    missing = result.loc[
        ~result["local_series_path"].map(
            lambda value: Path(value).is_dir() and any(Path(value).glob("*.dcm"))
        ),
        ["study_id", "coordinate_series_id"],
    ]
    if not missing.empty:
        raise RuntimeError(
            f"Faltan {len(missing)} rutas de series en {split}: "
            + str(missing.head(10).to_dict("records"))
        )

    result["cache_file"] = result.apply(
        lambda row: (
            f"{row['study_id']}__{row['coordinate_series_id']}__{row['side']}__"
            f"{str(row['level']).replace('-', '_')}__{int(row['coordinate_instance_number'])}.npy"
        ),
        axis=1,
    )
    if result["cache_file"].duplicated().any():
        duplicates = result.loc[result["cache_file"].duplicated(False), "cache_file"].head(10)
        raise RuntimeError(f"Nombres de caché duplicados: {duplicates.tolist()}")
    return result.reset_index(drop=True)


@lru_cache(maxsize=4096)
def _dicom_files(series_path_text: str) -> tuple[Path, ...]:
    series_path = Path(series_path_text)
    files = list(series_path.glob("*.dcm"))
    if not files:
        raise RuntimeError(f"Serie sin DICOM: {series_path}")

    def order(path: Path) -> tuple[int, str]:
        if path.stem.isdigit():
            return int(path.stem), path.name
        try:
            import pydicom

            header = pydicom.dcmread(
                path,
                stop_before_pixels=True,
                specific_tags=["InstanceNumber"],
            )
            return int(getattr(header, "InstanceNumber", 0)), path.name
        except Exception:
            return 0, path.name

    return tuple(sorted(files, key=order))


def _read_dicom(path: Path) -> np.ndarray:
    import pydicom

    dataset = pydicom.dcmread(path)
    image = dataset.pixel_array.astype(np.float32)
    slope = float(getattr(dataset, "RescaleSlope", 1.0))
    intercept = float(getattr(dataset, "RescaleIntercept", 0.0))
    return image * slope + intercept


def _crop(image: np.ndarray, x: float, y: float, size: int) -> np.ndarray:
    if image.ndim != 2:
        image = np.squeeze(image)
    if image.ndim != 2:
        raise RuntimeError(f"Se esperaba imagen 2D y se obtuvo shape={image.shape}")
    height, width = image.shape
    half = size // 2
    left = int(round(float(x))) - half
    top = int(round(float(y))) - half
    right = left + size
    bottom = top + size
    pad_left = max(0, -left)
    pad_top = max(0, -top)
    pad_right = max(0, right - width)
    pad_bottom = max(0, bottom - height)
    if any((pad_left, pad_top, pad_right, pad_bottom)):
        image = np.pad(
            image,
            ((pad_top, pad_bottom), (pad_left, pad_right)),
            mode="edge",
        )
        left += pad_left
        right += pad_left
        top += pad_top
        bottom += pad_top
    crop = image[top:bottom, left:right]
    if crop.shape != (size, size):
        raise RuntimeError(f"Crop inválido: {crop.shape}, esperado={(size, size)}")
    return crop


def _uint8_stack(stack: list[np.ndarray]) -> np.ndarray:
    joined = np.concatenate([array[np.isfinite(array)].ravel() for array in stack])
    if joined.size == 0:
        return np.zeros((len(stack), *stack[0].shape), dtype=np.uint8)
    low, high = np.percentile(joined, [1, 99])
    high = max(float(high), float(low) + 1.0)
    normalized = [
        (np.clip((array - low) / (high - low), 0.0, 1.0) * 255.0)
        .round()
        .astype(np.uint8)
        for array in stack
    ]
    return np.stack(normalized, axis=0)


def _resize_stack(stack: np.ndarray, image_size: int) -> np.ndarray:
    tensor = torch.from_numpy(stack).float()[None]
    resized = torch.nn.functional.interpolate(
        tensor,
        size=(image_size, image_size),
        mode="bilinear",
        align_corners=False,
    )[0]
    return resized.clamp(0, 255).round().byte().numpy()


def build_cache(
    samples: pd.DataFrame,
    cache_root: Path,
    split: str,
    config: TrainConfig,
) -> dict[str, Any]:
    target = cache_root / split
    target.mkdir(parents=True, exist_ok=True)
    built = 0
    reused = 0
    started = time.time()

    for series_path, group in tqdm(
        samples.groupby("local_series_path", sort=True),
        total=samples["local_series_path"].nunique(),
        desc=f"cache {split} por serie",
    ):
        pending = [
            row
            for row in group.itertuples(index=False)
            if not (target / str(row.cache_file)).is_file()
        ]
        reused += len(group) - len(pending)
        if not pending:
            continue

        files = _dicom_files(str(series_path))
        numeric_lookup = {
            int(path.stem): index
            for index, path in enumerate(files)
            if path.stem.isdigit()
        }
        image_cache: dict[int, np.ndarray] = {}

        for row in pending:
            instance = int(row.coordinate_instance_number)
            if numeric_lookup:
                center = numeric_lookup.get(instance)
                if center is None:
                    nearest_instance = min(
                        numeric_lookup,
                        key=lambda value: abs(value - instance),
                    )
                    center = numeric_lookup[nearest_instance]
            else:
                center = min(max(instance - 1, 0), len(files) - 1)

            indices = (
                max(0, center - 1),
                center,
                min(len(files) - 1, center + 1),
            )
            crops: list[np.ndarray] = []
            for index in indices:
                if index not in image_cache:
                    image_cache[index] = _read_dicom(files[index])
                crops.append(
                    _crop(
                        image_cache[index],
                        float(row.coordinate_x),
                        float(row.coordinate_y),
                        config.crop_size,
                    )
                )
            stack = _resize_stack(_uint8_stack(crops), config.image_size)
            destination = target / str(row.cache_file)
            temporary = destination.with_suffix(".tmp.npy")
            np.save(temporary, stack, allow_pickle=False)
            os.replace(temporary, destination)
            built += 1

    expected = len(samples)
    present = sum((target / name).is_file() for name in samples["cache_file"])
    if present != expected:
        raise RuntimeError(
            f"Caché incompleto para {split}: present={present}, expected={expected}"
        )
    return {
        "split": split,
        "expectedSamples": int(expected),
        "builtSamples": int(built),
        "reusedSamples": int(reused),
        "cacheFiles": int(present),
        "minutes": round((time.time() - started) / 60, 2),
    }


class CachedForaminalDataset(Dataset):
    mean = torch.tensor([0.485, 0.456, 0.406], dtype=torch.float32).view(3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225], dtype=torch.float32).view(3, 1, 1)

    def __init__(
        self,
        frame: pd.DataFrame,
        cache_root: Path,
        split: str,
        augment: bool,
    ) -> None:
        self.frame = frame.reset_index(drop=True)
        self.root = cache_root / split
        self.augment = augment

    def __len__(self) -> int:
        return len(self.frame)

    def __getitem__(self, index: int):
        from torchvision.transforms import InterpolationMode
        from torchvision.transforms import functional as transform_functional

        row = self.frame.iloc[index]
        image = torch.from_numpy(
            np.load(self.root / str(row["cache_file"]), allow_pickle=False)
        ).float() / 255.0

        if self.augment:
            if random.random() < 0.55:
                image = transform_functional.affine(
                    image,
                    angle=random.uniform(-4.0, 4.0),
                    translate=[random.randint(-6, 6), random.randint(-6, 6)],
                    scale=random.uniform(0.95, 1.05),
                    shear=[0.0, 0.0],
                    interpolation=InterpolationMode.BILINEAR,
                )
            if random.random() < 0.5:
                image = image * random.uniform(0.90, 1.10) + random.uniform(-0.04, 0.04)
                image = image.clamp(0.0, 1.0)

        image = (image - self.mean) / self.std
        return (
            image,
            int(row["severity_code"]),
            int(row["side_index"]),
            int(row["level_index"]),
            int(index),
        )


class ForaminalClassifier(nn.Module):
    def __init__(self, config: TrainConfig) -> None:
        super().__init__()
        import timm

        pretrained_loaded = bool(config.pretrained)
        try:
            backbone = timm.create_model(
                config.model_name,
                pretrained=config.pretrained,
                in_chans=3,
                num_classes=0,
                global_pool="avg",
            )
        except Exception as exc:
            print({"pretrainedFallback": True, "reason": str(exc)[:300]})
            pretrained_loaded = False
            backbone = timm.create_model(
                config.model_name,
                pretrained=False,
                in_chans=3,
                num_classes=0,
                global_pool="avg",
            )
        self.backbone = backbone
        self.side_embedding = nn.Embedding(len(SIDES), config.side_embedding_dim)
        self.level_embedding = nn.Embedding(len(LEVELS), config.level_embedding_dim)
        feature_dim = int(getattr(backbone, "num_features"))
        combined_dim = feature_dim + config.side_embedding_dim + config.level_embedding_dim
        self.head = nn.Sequential(
            nn.LayerNorm(combined_dim),
            nn.Dropout(config.dropout),
            nn.Linear(combined_dim, len(CLASS_NAMES)),
        )
        self.pretrained_loaded = pretrained_loaded
        self.feature_dim = feature_dim

    def forward(
        self,
        image: torch.Tensor,
        side_index: torch.Tensor,
        level_index: torch.Tensor,
    ) -> torch.Tensor:
        features = self.backbone(image)
        combined = torch.cat(
            [
                features,
                self.side_embedding(side_index),
                self.level_embedding(level_index),
            ],
            dim=1,
        )
        return self.head(combined)


def _set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def sampling_audit(train: pd.DataFrame) -> tuple[np.ndarray, dict[str, Any]]:
    class_counts = (
        train["severity_code"].value_counts().reindex(range(3), fill_value=0).sort_index()
    )
    stratum_counts = train["stratum"].value_counts()
    if (class_counts <= 0).any():
        raise RuntimeError(f"Clase vacía en train: {class_counts.to_dict()}")

    class_component = train["severity_code"].map(
        {index: 1.0 / math.sqrt(float(count)) for index, count in class_counts.items()}
    )
    stratum_component = train["stratum"].map(
        {key: 1.0 / float(count) ** 0.25 for key, count in stratum_counts.items()}
    )
    weights = (class_component * stratum_component).to_numpy(dtype=np.float64)
    weights /= max(float(weights.mean()), 1e-12)
    weights = np.clip(weights, 0.15, 20.0)

    audit = {
        "classCounts": {
            CLASS_NAMES[index]: int(class_counts.loc[index]) for index in range(3)
        },
        "minimumStratumCount": int(stratum_counts.min()),
        "maximumStratumCount": int(stratum_counts.max()),
        "samplingWeightMin": float(weights.min()),
        "samplingWeightMean": float(weights.mean()),
        "samplingWeightMax": float(weights.max()),
    }
    return weights, audit


def make_loaders(
    train: pd.DataFrame,
    validation: pd.DataFrame,
    cache_root: Path,
    config: TrainConfig,
):
    train_dataset = CachedForaminalDataset(train, cache_root, "train", augment=True)
    validation_dataset = CachedForaminalDataset(
        validation,
        cache_root,
        "validation",
        augment=False,
    )
    sample_weights, audit = sampling_audit(train)
    generator = torch.Generator()
    generator.manual_seed(config.seed)
    sampler = WeightedRandomSampler(
        torch.as_tensor(sample_weights, dtype=torch.double),
        num_samples=len(sample_weights),
        replacement=True,
        generator=generator,
    )
    common = {
        "batch_size": config.batch_size,
        "num_workers": config.num_workers,
        "pin_memory": True,
        "persistent_workers": config.num_workers > 0,
    }
    train_loader = DataLoader(train_dataset, sampler=sampler, **common)
    validation_loader = DataLoader(validation_dataset, shuffle=False, **common)
    return train_loader, validation_loader, audit


def _metrics(
    targets: list[int],
    predictions: list[int],
    probabilities: np.ndarray,
) -> dict[str, float]:
    recalls = recall_score(
        targets,
        predictions,
        labels=[0, 1, 2],
        average=None,
        zero_division=0,
    )
    result = {
        "macro_f1": float(
            f1_score(targets, predictions, average="macro", zero_division=0)
        ),
        "balanced_accuracy": float(balanced_accuracy_score(targets, predictions)),
        "normal_mild_recall": float(recalls[0]),
        "moderate_recall": float(recalls[1]),
        "severe_recall": float(recalls[2]),
        "weighted_log_loss": float(
            log_loss(targets, probabilities, labels=[0, 1, 2])
        ),
    }
    result["selection_score"] = float(
        0.40 * result["macro_f1"]
        + 0.25 * result["balanced_accuracy"]
        + 0.25 * result["severe_recall"]
        + 0.10 * result["moderate_recall"]
    )
    return result


def _group_metrics(predictions: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    group_specs = [
        ("side", ["side"]),
        ("level", ["level"]),
        ("side_level", ["side", "level"]),
    ]
    for group_type, columns in group_specs:
        grouper: Any = columns[0] if len(columns) == 1 else columns
        for key, group in predictions.groupby(grouper, sort=True):
            key_tuple = key if isinstance(key, tuple) else (key,)
            probabilities = group[["prob_normal_mild", "prob_moderate", "prob_severe"]].to_numpy()
            metrics = _metrics(
                group["target"].astype(int).tolist(),
                group["prediction"].astype(int).tolist(),
                probabilities,
            )
            row: dict[str, Any] = {
                "group_type": group_type,
                "group_key": "__".join(map(str, key_tuple)),
                "n": int(len(group)),
                "normal_mild_support": int((group["target"] == 0).sum()),
                "moderate_support": int((group["target"] == 1).sum()),
                "severe_support": int((group["target"] == 2).sum()),
            }
            row.update(metrics)
            rows.append(row)
    return pd.DataFrame(rows)


def _class_loss_weights(train: pd.DataFrame, config: TrainConfig) -> np.ndarray:
    counts = (
        train["severity_code"].value_counts().reindex(range(3), fill_value=0).sort_index()
    ).astype(float)
    if (counts <= 0).any():
        raise RuntimeError(f"Clase vacía: {counts.to_dict()}")
    weights = counts.sum() / (len(CLASS_NAMES) * counts)
    weights /= weights.mean()
    weights.loc[2] *= config.severe_loss_multiplier
    weights = weights.clip(lower=0.35, upper=8.0)
    return weights.to_numpy(dtype=np.float32)


def _make_scaler():
    try:
        return torch.amp.GradScaler("cuda")
    except (AttributeError, TypeError):
        return torch.cuda.amp.GradScaler()


def _run_epoch(
    model: ForaminalClassifier,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
    optimizer: torch.optim.Optimizer | None,
    scaler: Any,
    max_grad_norm: float,
) -> tuple[dict[str, float], pd.DataFrame]:
    training = optimizer is not None
    model.train(training)
    losses = 0.0
    targets: list[int] = []
    predictions: list[int] = []
    probabilities: list[list[float]] = []
    dataset_indices: list[int] = []
    context = torch.enable_grad() if training else torch.no_grad()

    with context:
        for images, labels, side_indices, level_indices, row_indices in tqdm(
            loader,
            leave=False,
            desc="train" if training else "validation",
        ):
            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)
            side_indices = side_indices.to(device, non_blocking=True)
            level_indices = level_indices.to(device, non_blocking=True)
            if training:
                optimizer.zero_grad(set_to_none=True)

            with torch.autocast(device_type="cuda", dtype=torch.float16):
                logits = model(images, side_indices, level_indices)
                loss = criterion(logits, labels)

            if training:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
                scaler.step(optimizer)
                scaler.update()

            batch_probabilities = torch.softmax(logits.detach(), dim=1)
            batch_predictions = batch_probabilities.argmax(dim=1)
            losses += float(loss.detach().cpu()) * len(labels)
            targets.extend(labels.detach().cpu().tolist())
            predictions.extend(batch_predictions.cpu().tolist())
            probabilities.extend(batch_probabilities.cpu().tolist())
            dataset_indices.extend(row_indices.tolist())

    probability_array = np.asarray(probabilities, dtype=np.float64)
    metrics = _metrics(targets, predictions, probability_array)
    metrics["loss"] = float(losses / len(loader.dataset))
    prediction_frame = pd.DataFrame(
        {
            "dataset_index": dataset_indices,
            "target": targets,
            "prediction": predictions,
            "prob_normal_mild": probability_array[:, 0],
            "prob_moderate": probability_array[:, 1],
            "prob_severe": probability_array[:, 2],
        }
    ).sort_values("dataset_index").reset_index(drop=True)
    return metrics, prediction_frame


def _save_checkpoint(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    torch.save(payload, temporary)
    os.replace(temporary, path)


def train_model(
    train_samples: pd.DataFrame,
    validation_samples: pd.DataFrame,
    cache_root: Path,
    checkpoint_root: Path,
    run_root: Path,
    manifest_hashes: dict[str, str],
    repo_ref: str,
    repo_sha: str,
    config: TrainConfig,
) -> dict[str, Any]:
    if not torch.cuda.is_available():
        raise RuntimeError("Seleccioná una GPU T4 o superior en Colab.")

    device = torch.device("cuda")
    _set_seed(config.seed)
    run_root.mkdir(parents=True, exist_ok=True)
    checkpoint_root.mkdir(parents=True, exist_ok=True)

    train_loader, validation_loader, sampling = make_loaders(
        train_samples,
        validation_samples,
        cache_root,
        config,
    )
    model = ForaminalClassifier(config).to(device)
    loss_weights = _class_loss_weights(train_samples, config)
    criterion = nn.CrossEntropyLoss(
        weight=torch.tensor(loss_weights, dtype=torch.float32, device=device),
        label_smoothing=config.label_smoothing,
    )
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=config.learning_rate,
        weight_decay=config.weight_decay,
    )
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max",
        factor=0.5,
        patience=1,
        min_lr=1e-6,
    )
    scaler = _make_scaler()

    history: list[dict[str, Any]] = []
    best_score = -math.inf
    best_epoch = 0
    stale_epochs = 0
    best_checkpoint = checkpoint_root / "best_checkpoint.pt"
    last_checkpoint = checkpoint_root / "last_checkpoint.pt"

    for epoch_number in range(1, config.max_epochs + 1):
        train_metrics, _ = _run_epoch(
            model,
            train_loader,
            criterion,
            device,
            optimizer,
            scaler,
            config.max_grad_norm,
        )
        validation_metrics, _ = _run_epoch(
            model,
            validation_loader,
            criterion,
            device,
            None,
            scaler,
            config.max_grad_norm,
        )
        scheduler.step(validation_metrics["selection_score"])
        record = {
            "epoch": epoch_number,
            "learning_rate": float(optimizer.param_groups[0]["lr"]),
            **{f"train_{key}": value for key, value in train_metrics.items()},
            **{
                f"validation_{key}": value
                for key, value in validation_metrics.items()
            },
        }
        history.append(record)
        print(record)

        checkpoint_payload = {
            "schemaVersion": "pfi.rsna-foraminal-training-checkpoint.v1",
            "modelStateDict": model.state_dict(),
            "optimizerStateDict": optimizer.state_dict(),
            "epoch": epoch_number,
            "config": asdict(config),
            "classNames": list(CLASS_NAMES),
            "displayClassNames": list(DISPLAY_CLASS_NAMES),
            "sideToIndex": SIDE_TO_INDEX,
            "levelToIndex": LEVEL_TO_INDEX,
            "manifestHashes": manifest_hashes,
            "repoRef": repo_ref,
            "repoSha": repo_sha,
            "pretrainedLoaded": bool(model.pretrained_loaded),
            "featureDim": int(model.feature_dim),
            "humanReviewRequired": True,
            "notClinicalDiagnosis": True,
            "officialTestAccessed": False,
            "internalTestAccessed": False,
            "validationMetrics": validation_metrics,
        }
        _save_checkpoint(last_checkpoint, checkpoint_payload)

        if validation_metrics["selection_score"] > best_score + 1e-6:
            best_score = float(validation_metrics["selection_score"])
            best_epoch = epoch_number
            stale_epochs = 0
            _save_checkpoint(best_checkpoint, checkpoint_payload)
        else:
            stale_epochs += 1
            if stale_epochs >= config.patience:
                print({"earlyStopping": True, "epoch": epoch_number})
                break

    if not best_checkpoint.is_file():
        raise RuntimeError("No se generó best_checkpoint.pt.")

    checkpoint = torch.load(best_checkpoint, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["modelStateDict"])
    best_metrics, predictions = _run_epoch(
        model,
        validation_loader,
        criterion,
        device,
        None,
        scaler,
        config.max_grad_norm,
    )
    metadata = validation_samples[
        [
            "sample_id",
            "study_id",
            "coordinate_series_id",
            "side",
            "level",
            "severity",
            "severity_code",
            "coordinate_instance_number",
        ]
    ].reset_index(drop=True)
    predictions = metadata.join(predictions.drop(columns=["dataset_index"]))
    predictions["predicted_severity"] = predictions["prediction"].map(
        {index: name for index, name in enumerate(CLASS_NAMES)}
    )
    group_metrics = _group_metrics(predictions)

    history_path = run_root / "training_history.csv"
    predictions_path = run_root / "validation_predictions.csv"
    groups_path = run_root / "validation_metrics_by_group.csv"
    sampling_path = run_root / "sampling_audit.json"
    model_card_path = run_root / "model_card.md"
    summary_path = run_root / "training_summary.json"

    pd.DataFrame(history).to_csv(history_path, index=False)
    predictions.to_csv(predictions_path, index=False)
    group_metrics.to_csv(groups_path, index=False)
    _atomic_write_json(
        sampling_path,
        {
            **sampling,
            "lossClassWeights": {
                CLASS_NAMES[index]: float(loss_weights[index]) for index in range(3)
            },
        },
    )

    process_gates = {
        "sourceNotebook58Approved": True,
        "trainValidationStudyIsolation": not bool(
            set(train_samples["study_id"]) & set(validation_samples["study_id"])
        ),
        "trainContainsAllClasses": set(train_samples["severity"]) == set(CLASS_NAMES),
        "validationContainsAllClasses": set(validation_samples["severity"])
        == set(CLASS_NAMES),
        "bestCheckpointExists": best_checkpoint.is_file(),
        "finiteValidationMetrics": all(
            math.isfinite(float(value)) for value in best_metrics.values()
        ),
        "internalTestNotAccessed": True,
        "officialTestNotAccessed": True,
        "humanReviewRequired": True,
        "notClinicalDiagnosis": True,
    }
    metric_gates = {
        "macroF1": best_metrics["macro_f1"] >= config.minimum_macro_f1,
        "balancedAccuracy": best_metrics["balanced_accuracy"]
        >= config.minimum_balanced_accuracy,
        "severeRecall": best_metrics["severe_recall"]
        >= config.minimum_severe_recall,
        "moderateRecall": best_metrics["moderate_recall"]
        >= config.minimum_moderate_recall,
    }
    approved = all(process_gates.values()) and all(metric_gates.values())

    model_card = f"""# RSNA foraminal Sagittal T1 2.5D — model card

- Estado: {'APPROVED_FOR_NOTEBOOK_60' if approved else 'TRAINING_REVIEW_REQUIRED'}
- Arquitectura: `{config.model_name}` con embeddings de lado y nivel.
- Entrada: crop 2.5D de tres cortes Sagittal T1 alrededor de la coordenada foraminal.
- Clases: Normal/Mild, Moderate, Severe.
- Mejor época: {best_epoch}
- Macro F1 de validación: {best_metrics['macro_f1']:.4f}
- Balanced accuracy de validación: {best_metrics['balanced_accuracy']:.4f}
- Recall Severe de validación: {best_metrics['severe_recall']:.4f}
- Recall Moderate de validación: {best_metrics['moderate_recall']:.4f}

## Uso previsto

Herramienta de investigación y apoyo con revisión humana obligatoria. No es diagnóstico clínico autónomo y no está aprobada para uso comercial.

## Separación de datos

El entrenamiento usa únicamente `train_manifest.csv` y `validation_manifest.csv` del Notebook 58. El internal test permanece sellado para el Notebook 60.
"""
    _atomic_write_text(model_card_path, model_card)

    summary: dict[str, Any] = {
        "schemaVersion": "pfi.rsna-foraminal-training.v1",
        "ticket": "P10.6-AI",
        "notebook": 59,
        "sourceNotebook": 58,
        "status": "APPROVED_FOR_NOTEBOOK_60" if approved else "TRAINING_REVIEW_REQUIRED",
        "approved": approved,
        "nextNotebook": 60 if approved else None,
        "createdAtUtc": datetime.now(timezone.utc).isoformat(),
        "task": "neural_foraminal_narrowing",
        "sequence": "Sagittal T1",
        "architecture": {
            "backbone": config.model_name,
            "input": "2.5D_three_adjacent_sagittal_slices",
            "sharedSides": True,
            "sideEmbedding": config.side_embedding_dim,
            "levelEmbedding": config.level_embedding_dim,
            "pretrainedLoaded": bool(model.pretrained_loaded),
        },
        "config": asdict(config),
        "data": {
            "trainRows": int(len(train_samples)),
            "trainStudies": int(train_samples["study_id"].nunique()),
            "validationRows": int(len(validation_samples)),
            "validationStudies": int(validation_samples["study_id"].nunique()),
            "internalTestAccessed": False,
        },
        "bestEpoch": int(best_epoch),
        "bestSelectionScore": float(best_score),
        "validationMetrics": best_metrics,
        "processGates": process_gates,
        "metricGates": metric_gates,
        "manifestHashes": manifest_hashes,
        "repoRef": repo_ref,
        "repoSha": repo_sha,
        "checkpoint": {
            "path": str(best_checkpoint),
            "sha256": sha256_file(best_checkpoint),
        },
        "governance": {
            "humanReviewRequired": True,
            "notClinicalDiagnosis": True,
            "autonomousDiagnosis": False,
            "commercialUse": False,
            "officialTestAccessed": False,
            "internalTestAccessed": False,
            "internalTestSealedUntilNotebook60": True,
        },
    }
    _atomic_write_json(summary_path, summary)
    summary["outputSha256"] = {
        "history": sha256_file(history_path),
        "validationPredictions": sha256_file(predictions_path),
        "validationMetricsByGroup": sha256_file(groups_path),
        "samplingAudit": sha256_file(sampling_path),
        "modelCard": sha256_file(model_card_path),
    }
    _atomic_write_json(summary_path, summary)
    return summary


__all__ = [
    "CLASS_NAMES",
    "DISPLAY_CLASS_NAMES",
    "LEVELS",
    "SIDES",
    "TrainConfig",
    "DataRootAudit",
    "audit_data_root",
    "build_cache",
    "download_selected_series",
    "find_data_root",
    "load_manifests",
    "prepare_samples",
    "sampling_audit",
    "sha256_file",
    "train_model",
]
