# P10.6-AI — Notebook 59: entrenamiento foraminal Sagittal T1

Entrena un clasificador **2.5D multiclase** para estrechamiento foraminal neural izquierdo y derecho usando exclusivamente `train_manifest.csv` y `validation_manifest.csv` del Notebook 58.

El modelo comparte el backbone entre ambos lados e incorpora embeddings explícitos de **lado** y **nivel lumbar**. El `internal_test` permanece sellado para el Notebook 60.

`humanReviewRequired=true` · `notClinicalDiagnosis=true` · `officialTestAccessed=false`


## Recursos y alcance

- Runtime recomendado: **Google Colab con GPU T4 o superior**.
- Autorizar Google Drive.
- No requiere token de GitHub.
- El token de Kaggle se solicita únicamente si las series Sagittal T1 necesarias no están disponibles en el runtime o en Drive.
- El notebook puede reanudarse: los crops `.npy` ya generados y el checkpoint se reutilizan.
- No abre ni carga `internal_test_manifest.csv`.


In [1]:
# 1) Dependencias mínimas
from __future__ import annotations
import importlib.util
import subprocess
import sys

packages = {
    "pydicom": "pydicom",
    "timm": "timm",
    "tqdm": "tqdm",
    "sklearn": "scikit-learn",
    "kaggle": "kaggle",
}
missing = [
    package
    for module, package in packages.items()
    if importlib.util.find_spec(module) is None
]
if missing:
    subprocess.check_call([
        sys.executable,
        "-m",
        "pip",
        "install",
        "--quiet",
        *missing,
    ])
print({"installedNow": missing})


{'installedNow': ['pydicom']}


In [2]:
# 2) GPU y Google Drive
import getpass
import json
import os
from pathlib import Path

import torch
from google.colab import drive  # type: ignore

if not torch.cuda.is_available():
    raise RuntimeError(
        "Seleccioná GPU T4 o superior: Entorno de ejecución > Cambiar tipo de entorno."
    )

print({
    "gpu": torch.cuda.get_device_name(0),
    "gpuMemoryGiB": round(
        torch.cuda.get_device_properties(0).total_memory / 1024**3,
        2,
    ),
    "torch": torch.__version__,
})
drive.mount("/content/drive", force_remount=False)


{'gpu': 'Tesla T4', 'gpuMemoryGiB': 14.56, 'torch': '2.11.0+cu128'}
Mounted at /content/drive


In [3]:
# 3) Clonar o actualizar la rama e importar el pipeline
REPO_URL = (
    "https://github.com/EnzoAA004/"
    "PFI_MVPTest_Enzo_AImodule.git"
)
REPO_REF = "enzo/p10-6-ai-rsna-findings"
REPO_ROOT = Path("/content/PFI_MVPTest_Enzo_AImodule")

if not (REPO_ROOT / ".git").exists():
    subprocess.check_call([
        "git",
        "clone",
        "--branch",
        REPO_REF,
        "--single-branch",
        REPO_URL,
        str(REPO_ROOT),
    ])
else:
    subprocess.check_call(
        ["git", "fetch", "origin", REPO_REF],
        cwd=REPO_ROOT,
    )
    subprocess.check_call(
        ["git", "checkout", REPO_REF],
        cwd=REPO_ROOT,
    )
    subprocess.check_call(
        ["git", "pull", "--ff-only", "origin", REPO_REF],
        cwd=REPO_ROOT,
    )

REPO_SHA = subprocess.check_output(
    ["git", "rev-parse", "HEAD"],
    cwd=REPO_ROOT,
    text=True,
).strip()

sys.path.insert(0, str(REPO_ROOT / "ai_service"))
from pfi_ai_service.training.rsna_foraminal_training import (
    TrainConfig,
    build_cache,
    download_selected_series,
    find_data_root,
    load_manifests,
    prepare_samples,
    train_model,
)

print({"repoRef": REPO_REF, "repoSha": REPO_SHA})


{'repoRef': 'enzo/p10-6-ai-rsna-findings', 'repoSha': '2e249dfffd869e98bc9d3659a70b08298eb9af67'}


In [4]:
# 4) Rutas y configuración
PFI_ROOT = Path("/content/drive/MyDrive/PFI_MVP")
RESULTS_ROOT = PFI_ROOT / "results" / "P10_6_rsna_findings"
SPLIT_ROOT = RESULTS_ROOT / "notebook58_foraminal_split"
RUN_ROOT = RESULTS_ROOT / "notebook59_foraminal_training"

MODEL_ROOT = (
    PFI_ROOT
    / "models"
    / "P10_6_rsna_findings"
    / "foraminal_sagittal_t1_2p5d"
)
CHECKPOINT_ROOT = MODEL_ROOT / "checkpoints"

LOCAL_DATA_ROOT = Path("/content/RSNA_LUMBAR_DISC")
DRIVE_DATA_ROOT = PFI_ROOT / "data" / "RSNA_LUMBAR_DISC"
CACHE_ROOT = Path("/content/rsna_foraminal_cache")
COMPETITION = "rsna-2024-lumbar-spine-degenerative-classification"

CFG = TrainConfig(
    seed=2026,
    image_size=224,
    crop_size=256,
    batch_size=32,
    num_workers=2,
    max_epochs=15,
    patience=5,
    learning_rate=2e-4,
    weight_decay=1e-4,
    model_name="efficientnet_b0",
    pretrained=True,
)

for path in (RUN_ROOT, MODEL_ROOT, CHECKPOINT_ROOT, CACHE_ROOT):
    path.mkdir(parents=True, exist_ok=True)

print(CFG)
print({
    "splitRoot": str(SPLIT_ROOT),
    "runRoot": str(RUN_ROOT),
    "checkpointRoot": str(CHECKPOINT_ROOT),
    "cacheRoot": str(CACHE_ROOT),
})


TrainConfig(seed=2026, image_size=224, crop_size=256, batch_size=32, num_workers=2, max_epochs=15, patience=5, learning_rate=0.0002, weight_decay=0.0001, model_name='efficientnet_b0', pretrained=True, side_embedding_dim=8, level_embedding_dim=12, dropout=0.25, label_smoothing=0.05, severe_loss_multiplier=1.25, max_grad_norm=2.0, minimum_macro_f1=0.36, minimum_balanced_accuracy=0.45, minimum_severe_recall=0.3, minimum_moderate_recall=0.25)
{'splitRoot': '/content/drive/MyDrive/PFI_MVP/results/P10_6_rsna_findings/notebook58_foraminal_split', 'runRoot': '/content/drive/MyDrive/PFI_MVP/results/P10_6_rsna_findings/notebook59_foraminal_training', 'checkpointRoot': '/content/drive/MyDrive/PFI_MVP/models/P10_6_rsna_findings/foraminal_sagittal_t1_2p5d/checkpoints', 'cacheRoot': '/content/rsna_foraminal_cache'}


## Carga y auditoría de datos

La función siguiente verifica hashes, aprobación del Notebook 58, separación por estudio y presencia de las tres clases. Solo lee los manifests de entrenamiento y validación; del internal test únicamente comprueba que el archivo sellado exista.


In [5]:
# 5) Cargar train y validation sin acceder al internal test
train_manifest, validation_manifest, split_summary, manifest_hashes = (
    load_manifests(SPLIT_ROOT)
)

distribution = (
    train_manifest.groupby(["side", "level", "severity"])
    .size()
    .rename("train_rows")
    .reset_index()
)
validation_distribution = (
    validation_manifest.groupby(["side", "level", "severity"])
    .size()
    .rename("validation_rows")
    .reset_index()
)

print({
    "trainRows": len(train_manifest),
    "trainStudies": train_manifest["study_id"].nunique(),
    "validationRows": len(validation_manifest),
    "validationStudies": validation_manifest["study_id"].nunique(),
    "trainClassCounts": train_manifest["severity"].value_counts().to_dict(),
    "validationClassCounts": validation_manifest["severity"].value_counts().to_dict(),
    "internalTestAccessed": False,
    "officialTestAccessed": False,
})
display(distribution)
display(validation_distribution)


{'trainRows': 13774, 'trainStudies': 1380, 'validationRows': 2960, 'validationStudies': 296, 'trainClassCounts': {'normal_mild': 10739, 'moderate': 2496, 'severe': 539}, 'validationClassCounts': {'normal_mild': 2311, 'moderate': 534, 'severe': 115}, 'internalTestAccessed': False, 'officialTestAccessed': False}


,side,level,severity,train_rows
0,left,L1-L2,moderate,42
1,left,L1-L2,normal_mild,1337
2,left,L1-L2,severe,1
3,left,L2-L3,moderate,119
4,left,L2-L3,normal_mild,1254
5,left,L2-L3,severe,7
6,left,L3-L4,moderate,279
7,left,L3-L4,normal_mild,1074
8,left,L3-L4,severe,27
9,left,L4-L5,moderate,443


,side,level,severity,validation_rows
0,left,L1-L2,moderate,14
1,left,L1-L2,normal_mild,282
2,left,L2-L3,moderate,30
3,left,L2-L3,normal_mild,265
4,left,L2-L3,severe,1
5,left,L3-L4,moderate,73
6,left,L3-L4,normal_mild,217
7,left,L3-L4,severe,6
8,left,L4-L5,moderate,99
9,left,L4-L5,normal_mild,184


In [6]:
# 6) Resolver las series Sagittal T1 requeridas
DATA_ROOT, data_audits = find_data_root(
    [LOCAL_DATA_ROOT, DRIVE_DATA_ROOT],
    train_manifest,
    validation_manifest,
)

print({
    "audits": [
        {
            "root": audit.root,
            "complete": audit.complete,
            "requiredSeries": audit.required_series,
            "missingSeries": audit.missing_series,
            "missingExamples": list(audit.missing_examples[:5]),
        }
        for audit in data_audits
    ]
})

if DATA_ROOT is None:
    token = getpass.getpass(
        "Pegá tu KAGGLE_API_TOKEN para descargar solo las series requeridas: "
    ).strip()
    DATA_ROOT = download_selected_series(
        train_manifest,
        validation_manifest,
        LOCAL_DATA_ROOT,
        COMPETITION,
        token,
    )
    token = ""
    os.environ.pop("KAGGLE_API_TOKEN", None)

print({
    "dataRoot": str(DATA_ROOT),
    "sequence": "Sagittal T1",
    "internalTestAccessed": False,
})


{'audits': [{'root': '/content/RSNA_LUMBAR_DISC', 'complete': False, 'requiredSeries': 1681, 'missingSeries': 1681, 'missingExamples': ['100206310/2092806862', '1002894806/866293114', '1004726367/2526352865', '1008446160/2539455828', '1009445512/3088482668']}, {'root': '/content/drive/MyDrive/PFI_MVP/data/RSNA_LUMBAR_DISC', 'complete': True, 'requiredSeries': 1681, 'missingSeries': 0, 'missingExamples': []}]}
{'dataRoot': '/content/drive/MyDrive/PFI_MVP/data/RSNA_LUMBAR_DISC', 'sequence': 'Sagittal T1', 'internalTestAccessed': False}


## Preparación 2.5D

Cada muestra usa tres cortes sagitales adyacentes (`centro-1`, `centro`, `centro+1`) alrededor de la coordenada foraminal. Se recorta una región de 256×256 y se redimensiona a 224×224. No se aplica espejo horizontal porque invertiría el eje anteroposterior.


In [7]:
# 7) Preparar muestras y construir/reutilizar caché local
train_samples = prepare_samples(train_manifest, DATA_ROOT, "train")
validation_samples = prepare_samples(
    validation_manifest,
    DATA_ROOT,
    "validation",
)

train_cache_audit = build_cache(
    train_samples,
    CACHE_ROOT,
    "train",
    CFG,
)
validation_cache_audit = build_cache(
    validation_samples,
    CACHE_ROOT,
    "validation",
    CFG,
)

print({
    "trainCache": train_cache_audit,
    "validationCache": validation_cache_audit,
    "internalTestAccessed": False,
})


cache train por serie:   0%|          | 0/1385 [00:00<?, ?it/s]

cache validation por serie:   0%|          | 0/296 [00:00<?, ?it/s]

{'trainCache': {'split': 'train', 'expectedSamples': 13774, 'builtSamples': 13774, 'reusedSamples': 0, 'cacheFiles': 13774, 'minutes': 83.71}, 'validationCache': {'split': 'validation', 'expectedSamples': 2960, 'builtSamples': 2960, 'reusedSamples': 0, 'cacheFiles': 2960, 'minutes': 17.99}, 'internalTestAccessed': False}


## Entrenamiento

El muestreo pondera simultáneamente la clase y el estrato `lado × nivel × severidad`. La selección del checkpoint combina macro F1, balanced accuracy, recall de `Severe` y recall de `Moderate`. El entrenamiento usa AMP, AdamW, reducción de learning rate y early stopping.


In [8]:
# 8) Entrenar y seleccionar el checkpoint usando validation
torch.cuda.empty_cache()

training_summary = train_model(
    train_samples,
    validation_samples,
    CACHE_ROOT,
    CHECKPOINT_ROOT,
    RUN_ROOT,
    manifest_hashes,
    repo_ref=REPO_REF,
    repo_sha=REPO_SHA,
    config=CFG,
)

print(json.dumps({
    "status": training_summary["status"],
    "approved": training_summary["approved"],
    "nextNotebook": training_summary["nextNotebook"],
    "bestEpoch": training_summary["bestEpoch"],
    "bestSelectionScore": training_summary["bestSelectionScore"],
    "validationMetrics": training_summary["validationMetrics"],
    "processGates": training_summary["processGates"],
    "metricGates": training_summary["metricGates"],
    "checkpoint": training_summary["checkpoint"],
    "internalTestAccessed": False,
}, indent=2, ensure_ascii=False))


model.safetensors: reconstructing file:   0%|          |  0.00B / 21.4MB            

model.safetensors: downloading bytes:           |  0.00B            

train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 1, 'learning_rate': 0.0002, 'train_macro_f1': 0.6040845371839967, 'train_balanced_accuracy': 0.6583915881348918, 'train_normal_mild_recall': 0.6408890242045974, 'train_moderate_recall': 0.39444949954504094, 'train_severe_recall': 0.9398362406550373, 'train_weighted_log_loss': 0.8709964231095123, 'train_selection_score': 0.6806357220255851, 'train_loss': 0.6272441188569371, 'validation_macro_f1': 0.4890437984360636, 'validation_balanced_accuracy': 0.5712749943612007, 'validation_normal_mild_recall': 0.7477282561661618, 'validation_moderate_recall': 0.42696629213483145, 'validation_severe_recall': 0.5391304347826087, 'validation_weighted_log_loss': 0.750064108937551, 'validation_selection_score': 0.5159155058738609, 'validation_loss': 1.081622236483806}


train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 2, 'learning_rate': 0.0002, 'train_macro_f1': 0.7985178636339362, 'train_balanced_accuracy': 0.8247716544147877, 'train_normal_mild_recall': 0.7892505677517032, 'train_moderate_recall': 0.7055606198723792, 'train_severe_recall': 0.9795037756202805, 'train_weighted_log_loss': 0.5286409555187327, 'train_selection_score': 0.8410320649495796, 'train_loss': 0.4211405489706796, 'validation_macro_f1': 0.5548227934335733, 'validation_balanced_accuracy': 0.5925469153624382, 'validation_normal_mild_recall': 0.8511466897446993, 'validation_moderate_recall': 0.45692883895131087, 'validation_severe_recall': 0.46956521739130436, 'validation_weighted_log_loss': 0.6182977197883485, 'validation_selection_score': 0.533150034456996, 'validation_loss': 1.0008309863709115}


train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 3, 'learning_rate': 0.0002, 'train_macro_f1': 0.8695389578189184, 'train_balanced_accuracy': 0.8854082137790814, 'train_normal_mild_recall': 0.8480085457042575, 'train_moderate_recall': 0.8196610169491525, 'train_severe_recall': 0.9885550786838341, 'train_weighted_log_loss': 0.3994767516196527, 'train_selection_score': 0.8982725079382115, 'train_loss': 0.3476276928495388, 'validation_macro_f1': 0.555703008617406, 'validation_balanced_accuracy': 0.6137756449105899, 'validation_normal_mild_recall': 0.8420597144093466, 'validation_moderate_recall': 0.47752808988764045, 'validation_severe_recall': 0.5217391304347826, 'validation_weighted_log_loss': 0.6249884021436307, 'validation_selection_score': 0.5539127062720697, 'validation_loss': 0.9637595714749516}


train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 4, 'learning_rate': 0.0002, 'train_macro_f1': 0.9121875631720434, 'train_balanced_accuracy': 0.9237772299078837, 'train_normal_mild_recall': 0.889807576668671, 'train_moderate_recall': 0.8852087114337568, 'train_severe_recall': 0.9963154016212233, 'train_weighted_log_loss': 0.32129350931497463, 'train_selection_score': 0.9334190542944699, 'train_loss': 0.3080483114440711, 'validation_macro_f1': 0.5951860462078994, 'validation_balanced_accuracy': 0.6194763976406836, 'validation_normal_mild_recall': 0.87321505841627, 'validation_moderate_recall': 0.5243445692883895, 'validation_severe_recall': 0.4608695652173913, 'validation_weighted_log_loss': 0.6164788508082008, 'validation_selection_score': 0.5605953661265175, 'validation_loss': 0.973122222359116}


train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 5, 'learning_rate': 0.0002, 'train_macro_f1': 0.9312270364630594, 'train_balanced_accuracy': 0.93915358950055, 'train_normal_mild_recall': 0.9154101326899879, 'train_moderate_recall': 0.9069767441860465, 'train_severe_recall': 0.9950738916256158, 'train_weighted_log_loss': 0.2767649952031232, 'train_selection_score': 0.9467453592853698, 'train_loss': 0.2791028052451598, 'validation_macro_f1': 0.5871378686548426, 'validation_balanced_accuracy': 0.5833507529544009, 'validation_normal_mild_recall': 0.9151882302033751, 'validation_moderate_recall': 0.3913857677902622, 'validation_severe_recall': 0.4434782608695652, 'validation_weighted_log_loss': 0.59777167277378, 'validation_selection_score': 0.5307009776969548, 'validation_loss': 0.9687878711803539}


train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 6, 'learning_rate': 0.0001, 'train_macro_f1': 0.9483244793119697, 'train_balanced_accuracy': 0.9542288364487604, 'train_normal_mild_recall': 0.9315901489814533, 'train_moderate_recall': 0.9365115228197017, 'train_severe_recall': 0.9945848375451264, 'train_weighted_log_loss': 0.24166543824413944, 'train_selection_score': 0.9601843625052298, 'train_loss': 0.26560739292684066, 'validation_macro_f1': 0.5820653344499047, 'validation_balanced_accuracy': 0.575162565709951, 'validation_normal_mild_recall': 0.8498485504110774, 'validation_moderate_recall': 0.5973782771535581, 'validation_severe_recall': 0.2782608695652174, 'validation_weighted_log_loss': 0.6154446869313595, 'validation_selection_score': 0.5059198203141098, 'validation_loss': 1.0287094721923002}


train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 7, 'learning_rate': 0.0001, 'train_macro_f1': 0.9717540154065025, 'train_balanced_accuracy': 0.9752206160304553, 'train_normal_mild_recall': 0.9603870577562745, 'train_moderate_recall': 0.9670903313663186, 'train_severe_recall': 0.9981844589687727, 'train_weighted_log_loss': 0.18999459220142795, 'train_selection_score': 0.9787619080490397, 'train_loss': 0.23786678828468893, 'validation_macro_f1': 0.611987785934042, 'validation_balanced_accuracy': 0.5981927093231179, 'validation_normal_mild_recall': 0.88749459108611, 'validation_moderate_recall': 0.550561797752809, 'validation_severe_recall': 0.3565217391304348, 'validation_weighted_log_loss': 0.6003078194830033, 'validation_selection_score': 0.5385299062622859, 'validation_loss': 0.9872756887126614}


train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 8, 'learning_rate': 5e-05, 'train_macro_f1': 0.9802609875742704, 'train_balanced_accuracy': 0.9824843239432739, 'train_normal_mild_recall': 0.9719669117647058, 'train_moderate_recall': 0.9758410476405509, 'train_severe_recall': 0.9996450124245652, 'train_weighted_log_loss': 0.16717580251852585, 'train_selection_score': 0.985220833885723, 'train_loss': 0.2239009249023417, 'validation_macro_f1': 0.6122435660433204, 'validation_balanced_accuracy': 0.5998650962912919, 'validation_normal_mild_recall': 0.9177845088706188, 'validation_moderate_recall': 0.46441947565543074, 'validation_severe_recall': 0.41739130434782606, 'validation_weighted_log_loss': 0.5990528602403578, 'validation_selection_score': 0.5456534741426508, 'validation_loss': 0.9735214529810725}


train:   0%|          | 0/431 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(


{'epoch': 9, 'learning_rate': 5e-05, 'train_macro_f1': 0.9866049181566042, 'train_balanced_accuracy': 0.9886903297695852, 'train_normal_mild_recall': 0.9785767790262172, 'train_moderate_recall': 0.9874942102825383, 'train_severe_recall': 1.0, 'train_weighted_log_loss': 0.1510503143498288, 'train_selection_score': 0.9905639707332918, 'train_loss': 0.2187002324886621, 'validation_macro_f1': 0.607643038605289, 'validation_balanced_accuracy': 0.581804734280257, 'validation_normal_mild_recall': 0.9251406317611424, 'validation_moderate_recall': 0.4550561797752809, 'validation_severe_recall': 0.3652173913043478, 'validation_weighted_log_loss': 0.5829398028481982, 'validation_selection_score': 0.5253183648157949, 'validation_loss': 0.9931401652258796}
{'earlyStopping': True, 'epoch': 9}


validation:   0%|          | 0/93 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: The y_pred values do not sum to one. Make sure to pass probabilities.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:3001: UserWarning: T

{
  "status": "APPROVED_FOR_NOTEBOOK_60",
  "approved": true,
  "nextNotebook": 60,
  "bestEpoch": 4,
  "bestSelectionScore": 0.5605953661265175,
  "validationMetrics": {
    "macro_f1": 0.5951860462078994,
    "balanced_accuracy": 0.6194763976406836,
    "normal_mild_recall": 0.87321505841627,
    "moderate_recall": 0.5243445692883895,
    "severe_recall": 0.4608695652173913,
    "weighted_log_loss": 0.6164788508082008,
    "selection_score": 0.5605953661265175,
    "loss": 0.973122222359116
  },
  "processGates": {
    "sourceNotebook58Approved": true,
    "trainValidationStudyIsolation": true,
    "trainContainsAllClasses": true,
    "validationContainsAllClasses": true,
    "bestCheckpointExists": true,
    "finiteValidationMetrics": true,
    "internalTestNotAccessed": true,
    "officialTestNotAccessed": true,
    "humanReviewRequired": true,
    "notClinicalDiagnosis": true
  },
  "metricGates": {
    "macroF1": true,
    "balancedAccuracy": true,
    "severeRecall": true,
    "

In [9]:
# 9) Gate final y evidencia generada
required_outputs = [
    "training_history.csv",
    "validation_predictions.csv",
    "validation_metrics_by_group.csv",
    "sampling_audit.json",
    "model_card.md",
    "training_summary.json",
]
missing_outputs = [
    name for name in required_outputs
    if not (RUN_ROOT / name).is_file()
]

if missing_outputs:
    raise RuntimeError(f"Faltan outputs del Notebook 59: {missing_outputs}")
if not (CHECKPOINT_ROOT / "best_checkpoint.pt").is_file():
    raise RuntimeError("No se generó best_checkpoint.pt.")

print({
    "status": training_summary["status"],
    "outputs": required_outputs,
    "bestCheckpoint": str(CHECKPOINT_ROOT / "best_checkpoint.pt"),
    "internalTestSealedUntilNotebook60": True,
    "officialTestAccessed": False,
    "humanReviewRequired": True,
    "notClinicalDiagnosis": True,
})

if not training_summary["approved"]:
    raise RuntimeError(
        "El entrenamiento terminó, pero no superó todos los gates de validación. "
        "Revisar training_summary.json antes del Notebook 60."
    )


{'status': 'APPROVED_FOR_NOTEBOOK_60', 'outputs': ['training_history.csv', 'validation_predictions.csv', 'validation_metrics_by_group.csv', 'sampling_audit.json', 'model_card.md', 'training_summary.json'], 'bestCheckpoint': '/content/drive/MyDrive/PFI_MVP/models/P10_6_rsna_findings/foraminal_sagittal_t1_2p5d/checkpoints/best_checkpoint.pt', 'internalTestSealedUntilNotebook60': True, 'officialTestAccessed': False, 'humanReviewRequired': True, 'notClinicalDiagnosis': True}


## Conclusión esperada

Una ejecución aprobada termina con `APPROVED_FOR_NOTEBOOK_60`. El checkpoint seleccionado y sus métricas quedan congelados en Drive. Recién el Notebook 60 podrá abrir el `internal_test_manifest.csv` para realizar una única evaluación final y decidir la exportación del modelo.
