#!/usr/bin/env bash
set -Eeuo pipefail
umask 077
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_CHECKOUT_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || true)"
[[ -n "$REPO_CHECKOUT_ROOT" ]] || REPO_CHECKOUT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd -P)"
ENV_FILE=""; COMPONENT=all; EXECUTE=0; REQUIRE_RESUME=0; RESULT=SUCCESS; REMOTE_BYTES_TOTAL=0
log(){ printf '[%s] %s\n' "$1" "$2" >&2; }
info(){ log INFO "$*"; }; warn(){ log WARN "$*"; }; err(){ log ERROR "$*"; }; dry(){ log DRY-RUN "$*"; }; pass(){ log PASS "$*"; }
trap 'err "fallo en linea $LINENO: $BASH_COMMAND"; exit 1' ERR
usage(){ cat <<'USAGE'
Uso: download-training-data.sh [--env-file PATH] [--component spider|axial|metadata|bootstrap|resume|datasets|all] [--dry-run|--execute] [--require-resume]
Descarga datasets/resume desde GCS al disco local. Default: dry-run. No borra archivos locales ni remotos.
USAGE
}
while [[ $# -gt 0 ]]; do case "$1" in --env-file) [[ $# -ge 2 ]] || exit 2; ENV_FILE="$2"; shift 2;; --component) [[ $# -ge 2 ]] || exit 2; COMPONENT="$2"; shift 2;; --dry-run) [[ "$EXECUTE" -eq 0 ]] || { err "--dry-run y --execute son incompatibles"; exit 2; }; EXECUTE=0; shift;; --execute) EXECUTE=1; shift;; --require-resume) REQUIRE_RESUME=1; shift;; --help) usage; exit 0;; *) err "argumento desconocido: $1"; usage >&2; exit 2;; esac; done
case "$COMPONENT" in spider|axial|metadata|bootstrap|resume|datasets|all) ;; *) err "component invalido: $COMPONENT"; exit 2;; esac
if [[ "$REQUIRE_RESUME" -eq 1 && "$COMPONENT" != resume && "$COMPONENT" != all ]]; then err "--require-resume solo aplica a resume o all"; exit 2; fi
select_env(){ if [[ -n "$ENV_FILE" ]]; then printf '%s\n' "$ENV_FILE"; elif [[ -f "$SCRIPT_DIR/training-vm.env" ]]; then printf '%s\n' "$SCRIPT_DIR/training-vm.env"; else printf '%s\n' "$SCRIPT_DIR/training-vm.env.example"; fi; }
load_env(){ ENV_FILE="$(select_env)"; [[ -f "$ENV_FILE" ]] || { err "env-file inexistente"; exit 2; }; set -a; source "$ENV_FILE"; set +a; }
need(){ local n="$1"; local -n ref="$n"; [[ -n "${ref-}" ]] || { err "variable requerida ausente: $n"; exit 2; }; }
bool(){ local n="$1"; local -n ref="$n"; local v="${ref-}"; [[ "$v" == 0 || "$v" == 1 ]] || { err "$n debe ser 0/1"; exit 2; }; }
run_id_ok(){ [[ "$PFI_RUN_ID" =~ ^[a-z0-9][a-z0-9-]{0,62}$ ]] || { err "PFI_RUN_ID invalido"; exit 2; }; }
norm(){ if command -v realpath >/dev/null 2>&1; then realpath -m "$1"; else printf '%s\n' "$1"; fi; }
path_ok(){ local n="$1" root val v; local -n ref="$n"; v="${ref-}"; [[ -n "$v" && "$v" == /* && "$v" != / ]] || { err "$n ruta insegura"; exit 2; }; root="$(norm "$PFI_VM_ROOT")"; val="$(norm "$v")"; [[ "$val" != *'/../'* && "$val" != */.. && "$val" != ..* ]] || { err "$n contiene .."; exit 2; }; [[ "$val" == "$root" || "$val" == "$root"/* ]] || { err "$n fuera de PFI_VM_ROOT"; exit 2; }; }
uri_ok(){ local n="$1" u b="${PFI_GCS_BUCKET_URI%/}"; local -n ref="$n"; u="${ref-}"; [[ "$u" == gs://* ]] || { err "$n no es gs://"; exit 2; }; [[ "${u%/}" != "$b" ]] || { err "$n no puede ser raiz bucket"; exit 2; }; [[ "${u%/}" == "$b"/* ]] || { err "$n fuera de bucket"; exit 2; }; }
validate_env(){ local v; for v in PFI_GCP_PROJECT_ID PFI_GCP_ZONE PFI_VM_NAME PFI_VM_SERVICE_ACCOUNT PFI_RUN_ID PFI_VM_ROOT PFI_DATA_ROOT PFI_LOCAL_RESUME_DIR PFI_GCS_BUCKET_URI PFI_GCS_SPIDER_URI PFI_GCS_AXIAL_URI PFI_GCS_METADATA_URI PFI_GCS_BOOTSTRAP_MODELS_URI PFI_GCS_RUN_RESUME_URI PFI_DOWNLOAD_RESUME PFI_SYNC_DRY_RUN PFI_MIN_FREE_DISK_GB SPIDER_IMAGES_DIR SPIDER_MASKS_DIR SPIDER_LABEL_GROUP_MAPPING_JSON SPIDER_CHECKPOINT_FOR_LABEL_MAP AXIAL_IMAGES_DIR AXIAL_MASKS_DIR AXIAL_E9_CURATED_SPLIT_CSV; do need "$v"; done; bool PFI_DOWNLOAD_RESUME; bool PFI_SYNC_DRY_RUN; run_id_ok; for v in PFI_GCS_SPIDER_URI PFI_GCS_AXIAL_URI PFI_GCS_METADATA_URI PFI_GCS_BOOTSTRAP_MODELS_URI PFI_GCS_RUN_RESUME_URI; do uri_ok "$v"; done; for v in PFI_DATA_ROOT PFI_LOCAL_RESUME_DIR SPIDER_IMAGES_DIR SPIDER_MASKS_DIR SPIDER_LABEL_GROUP_MAPPING_JSON SPIDER_CHECKPOINT_FOR_LABEL_MAP AXIAL_IMAGES_DIR AXIAL_MASKS_DIR AXIAL_E9_CURATED_SPLIT_CSV; do path_ok "$v"; done; [[ -z "${GOOGLE_APPLICATION_CREDENTIALS:-}" ]] || { err "GOOGLE_APPLICATION_CREDENTIALS definido"; exit 2; }; [[ "$AXIAL_IMAGES_DIR" == "$AXIAL_MASKS_DIR" ]] || { err "AXIAL_IMAGES_DIR y AXIAL_MASKS_DIR difieren; requiere estrategia explicita"; exit 2; }; [[ "$(dirname "$SPIDER_LABEL_GROUP_MAPPING_JSON")" == "$(dirname "$AXIAL_E9_CURATED_SPLIT_CSV")" ]] || { err "metadata local debe compartir directorio"; exit 2; }; }
metadata_get(){ curl -fsS --max-time 2 -H 'Metadata-Flavor: Google' "http://metadata.google.internal/computeMetadata/v1/$1"; }
check_execute_env(){ [[ "$(uname -s)" == Linux ]] || { err "--execute requiere Linux/GCE"; exit 1; }; for c in gcloud curl df find awk python3; do command -v "$c" >/dev/null || { err "comando faltante: $c"; exit 1; }; done; local p i z e; p="$(metadata_get project/project-id 2>/dev/null || true)"; i="$(metadata_get instance/name 2>/dev/null || true)"; z="$(metadata_get instance/zone 2>/dev/null || true)"; e="$(metadata_get instance/service-accounts/default/email 2>/dev/null || true)"; [[ "$p" == "$PFI_GCP_PROJECT_ID" && "$i" == "$PFI_VM_NAME" && "${z##*/}" == "$PFI_GCP_ZONE" && "$e" == "$PFI_VM_SERVICE_ACCOUNT" ]] || { err "metadata GCE no coincide"; exit 1; }; for d in "$PFI_DATA_ROOT" "$PFI_LOCAL_RESUME_DIR"; do [[ -d "$d" && -w "$d" ]] || { err "destino no existe/escribible: $d"; exit 1; }; done; gcloud storage ls "$PFI_GCS_BUCKET_URI/" >/dev/null || { err "bucket no listable"; exit 1; }; }
inspect_prefix(){ local label="$1" uri="$2" required="$3" out rc lower du bytes; set +eE; out="$(gcloud storage ls "$uri/" 2>&1)"; rc=$?; set -eE; lower="$(printf '%s' "$out"|tr '[:upper:]' '[:lower:]')"; if [[ "$rc" -ne 0 ]]; then if printf '%s' "$lower"|grep -Eq 'denied|forbidden|permission'; then err "$label permiso denegado"; exit 1; fi; if printf '%s' "$lower"|grep -Eq 'matched no objects|no urls matched|no objects|url matched no objects'; then if [[ "$required" == required ]]; then err "$label vacio"; exit 1; fi; warn "$label vacio; se omite"; printf '0 0\n'; return 0; fi; err "$label error desconocido al listar"; exit 1; fi; local objects; objects="$(printf '%s\n' "$out"|grep -Ev '/$'|grep -c . || true)"; if [[ "$objects" -eq 0 ]]; then if [[ "$required" == required ]]; then err "$label vacio"; exit 1; fi; warn "$label vacio; se omite"; printf '0 0\n'; return 0; fi; set +eE; du="$(gcloud storage du --summarize "$uri/" 2>/dev/null)"; set -eE; bytes="$(printf '%s\n' "$du"|awk '{print $1}'|tail -n1)"; [[ "$bytes" =~ ^[0-9]+$ ]] || bytes=0; info "$label source=$uri objetos=$objects bytes=$bytes"; printf '%s %s\n' "$objects" "$bytes"; }
add_transfer(){ local label="$1" source="$2" dest="$3" required="$4"; TRANSFERS_LABEL+=("$label"); TRANSFERS_SRC+=("$source"); TRANSFERS_DST+=("$dest"); TRANSFERS_REQ+=("$required"); }
build_transfers(){ TRANSFERS_LABEL=(); TRANSFERS_SRC=(); TRANSFERS_DST=(); TRANSFERS_REQ=(); case "$COMPONENT" in spider) add_transfer spider-images "$PFI_GCS_SPIDER_URI/images" "$SPIDER_IMAGES_DIR" required; add_transfer spider-masks "$PFI_GCS_SPIDER_URI/masks" "$SPIDER_MASKS_DIR" required;; axial) add_transfer axial "$PFI_GCS_AXIAL_URI" "$AXIAL_IMAGES_DIR" required;; metadata) add_transfer metadata "$PFI_GCS_METADATA_URI" "$(dirname "$SPIDER_LABEL_GROUP_MAPPING_JSON")" required;; bootstrap) add_transfer bootstrap "$PFI_GCS_BOOTSTRAP_MODELS_URI" "$(dirname "$SPIDER_CHECKPOINT_FOR_LABEL_MAP")" optional;; resume) add_transfer resume "$PFI_GCS_RUN_RESUME_URI" "$PFI_LOCAL_RESUME_DIR" resume;; datasets) add_transfer spider-images "$PFI_GCS_SPIDER_URI/images" "$SPIDER_IMAGES_DIR" required; add_transfer spider-masks "$PFI_GCS_SPIDER_URI/masks" "$SPIDER_MASKS_DIR" required; add_transfer axial "$PFI_GCS_AXIAL_URI" "$AXIAL_IMAGES_DIR" required; add_transfer metadata "$PFI_GCS_METADATA_URI" "$(dirname "$SPIDER_LABEL_GROUP_MAPPING_JSON")" required; add_transfer bootstrap "$PFI_GCS_BOOTSTRAP_MODELS_URI" "$(dirname "$SPIDER_CHECKPOINT_FOR_LABEL_MAP")" optional;; all) build_all;; esac; }
build_all(){ add_transfer spider-images "$PFI_GCS_SPIDER_URI/images" "$SPIDER_IMAGES_DIR" required; add_transfer spider-masks "$PFI_GCS_SPIDER_URI/masks" "$SPIDER_MASKS_DIR" required; add_transfer axial "$PFI_GCS_AXIAL_URI" "$AXIAL_IMAGES_DIR" required; add_transfer metadata "$PFI_GCS_METADATA_URI" "$(dirname "$SPIDER_LABEL_GROUP_MAPPING_JSON")" required; add_transfer bootstrap "$PFI_GCS_BOOTSTRAP_MODELS_URI" "$(dirname "$SPIDER_CHECKPOINT_FOR_LABEL_MAP")" optional; [[ "$PFI_DOWNLOAD_RESUME" == 1 ]] && add_transfer resume "$PFI_GCS_RUN_RESUME_URI" "$PFI_LOCAL_RESUME_DIR" resume || true; }
check_disk(){ [[ "$EXECUTE" -eq 1 ]] || return 0; local avail reserve need; avail="$(df -Pk "$PFI_DATA_ROOT"|awk 'NR==2{print $4*1024}')"; reserve=$((PFI_MIN_FREE_DISK_GB*1024*1024*1024)); need=$((REMOTE_BYTES_TOTAL+reserve)); info "disco disponible=$avail bytes remoto=$REMOTE_BYTES_TOTAL reserva=$reserve"; (( avail >= need )) || { err "espacio insuficiente antes de descargar"; exit 1; }; }
do_transfer(){ local label="$1" src="$2" dst="$3" objects="$4"; [[ "$objects" -gt 0 ]] || return 0; info "transferencia $label -> $dst modo=$([[ $EXECUTE -eq 1 ]] && printf execute || printf dry-run)"; if [[ "$EXECUTE" -eq 1 ]]; then gcloud storage rsync "$src" "$dst" --recursive; else dry "gcloud storage rsync $src $dst --recursive --dry-run"; gcloud storage rsync "$src" "$dst" --recursive --dry-run; fi; }
post_validate(){ [[ "$EXECUTE" -eq 1 ]] || return 0; case "$COMPONENT" in spider|datasets|all) [[ -n "$(find "$SPIDER_IMAGES_DIR" -type f -print -quit)" && -n "$(find "$SPIDER_MASKS_DIR" -type f -print -quit)" ]] || { err "SPIDER incompleto tras descarga"; exit 1; };; esac; case "$COMPONENT" in axial|datasets|all) [[ -n "$(find "$AXIAL_IMAGES_DIR" -type f -print -quit)" ]] || { err "AXIAL vacio tras descarga"; exit 1; };; esac; case "$COMPONENT" in metadata|datasets|all) python3 -c 'import json,sys,pandas as pd; d=json.load(open(sys.argv[1],encoding="utf-8")); assert isinstance(d,dict) and d; assert len(pd.read_csv(sys.argv[2]))>0' "$SPIDER_LABEL_GROUP_MAPPING_JSON" "$AXIAL_E9_CURATED_SPLIT_CSV" || { err "metadata invalida tras descarga"; exit 1; };; esac; if [[ "$COMPONENT" == resume || "$COMPONENT" == all ]]; then info "resume last=$(find "$PFI_LOCAL_RESUME_DIR" -name '*.last_checkpoint.pt' -type f|wc -l) best=$(find "$PFI_LOCAL_RESUME_DIR" -name '*.best_checkpoint.pt' -type f|wc -l)"; fi; }
main(){ load_env; validate_env; [[ "$EXECUTE" -eq 1 ]] && check_execute_env || info "modo dry-run por default; --execute requerido para transferir"; build_transfers; local i meta objects bytes; for i in "${!TRANSFERS_LABEL[@]}"; do local req="${TRANSFERS_REQ[$i]}"; [[ "$req" == resume && "$REQUIRE_RESUME" -eq 1 ]] && req=required; meta="$(inspect_prefix "${TRANSFERS_LABEL[$i]}" "${TRANSFERS_SRC[$i]}" "$req")"; objects="${meta%% *}"; bytes="${meta##* }"; REMOTE_BYTES_TOTAL=$((REMOTE_BYTES_TOTAL+bytes)); PLAN_OBJECTS+=("$objects"); PLAN_BYTES+=("$bytes"); done; check_disk; for i in "${!TRANSFERS_LABEL[@]}"; do do_transfer "${TRANSFERS_LABEL[$i]}" "${TRANSFERS_SRC[$i]}" "${TRANSFERS_DST[$i]}" "${PLAN_OBJECTS[$i]}"; done; post_validate; pass "SUCCESS component=$COMPONENT remote_bytes=$REMOTE_BYTES_TOTAL"; }
main "$@"
